### ISSUE TITLE
Strange interaction between unification variables and lambdas

### ISSUE THREAD

**Issue by plt-amy** [liamoc/holbert#8]
Gist demonstrating the issue: https://gist.github.com/plt-amy/a6d38244540ce1c4f5d928c164c6dcbc
Try applying the `pi-elim` rule; You'll see that the first goal we obtain is for a derivation of

```
p : (Π (? a A p) (x. T a))
```

rather than the

```
p : (Π (? a A p) (x. T (? a A p x)))
```

I would expect. I wish I could be more specific about the title.

**Comment by liamoc** [comment]
Hi Amelia, thanks for trying Holbert.
The solver Holbert uses is based on pattern unification and the `pi-elim` rule you have there is not in pattern form in the conclusion. This means that Holbert is picking the wrong solution for the metavariable B, resulting in a different goal than what you want.

However, because this is a common pattern with elimination rules specifically, we have some special case logic for them. Rather than applying the elimination rule as an introduction rule, explicitly eliminate the assumption you want (assumption 0) by clicking on it in the side bar and then selecting the relevant rule. This completes the unification correctly.
